### ISSUE TITLE
RESO Web Example Fails in Util.php

### ISSUE THREAD

**Issue by peterwerren** [RESO-RETS/RESOWebAPIReferenceClientinPHP#6]
### Description

Failure in /examples/web-example/index.php.
Suspected _config.php issue.

### Steps to Reproduce

Run:

https://re124.com/RESO/examples/web-example/index.php

**Expected behavior:** Log in confirmation; possibly access token.

**Actual behavior:** 1. Unzipped github samples.
2. Set up in GoDaddy directories.
3. PHP, curl, etc., all active.
4. Set _config as follows:

<?php

// API authentication URL
$api_auth_url = "https://op.api.crmls.org/identity/connect/authorize";

// API token URL
$api_token_url = "https://op.api.crmls.org/identity/connect/token";

// API data request (web) URL
$api_request_url = "https://h.api.crmls.org/RESO/OData/";

// API user name
$auth_username = "SMARTREIS";

// API password
$auth_password = "n39DWP?L";

// API client ID
$client_id = "SMARTREIS";

// API secret key
$client_secret = "n39DWP?L";

// Redirect URI
$redirect_uri = "https://openid.reso.org/";

// Scope
$scope = "ODataApi";

if(file_exists("/_config.php")) {
    require_once("/_config.php");
}
;

?>

5. Ran .../examples/web-example/index.php
from my directory.

6. Got login screen with my creds pre-filled.
7. Clicked "Login".
8. Error log:

[09-Sep-2019 22:55:23 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getAttribute() on null in /home/peterwerrenrath1/public_html/SREIS_SEARCH_ENGINE/RESO/lib/Util/Util.php:77
Stack trace:
#0 /home/peterwerrenrath1/public_html/SREIS_SEARCH_ENGINE/RESO/lib/OpenIDConnect.php(43): RESO\Util\Util::extractFormParameters('<!DOCTYPE html>...')
#1 /home/peterwerrenrath1/public_html/SREIS_SEARCH_ENGINE/RESO/examples/web-example/index.php(61): RESO\OpenIDConnect::authorize('SMARTREIS', 'n39DWP?L', 'https://openid....', 'ODataApi')
#2 {main}
  thrown in /home/peterwerrenrath1/public_html/SREIS_SEARCH_ENGINE/RESO/lib/Util/Util.php on line 77

9. Unclear how to resolve.  Suspect _config.php file issue.

**Reproduces how often:** Every time.

### Versions

PHP logo
PHP Version 7.1.30
System	Linux p3plcpnl0649.prod.phx3.secureserver.net 2.6.32-954.3.5.lve1.4.66.el6.x86_64 #1 SMP Thu Jun 20 11:00:35 EDT 2019 x86_64
Build Date	Jul 4 2019 18:09:57
Configure Command	'./configure' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--target=x86_64-redhat-linux-gnu' '--program-prefix=' '--prefix=/opt/alt/php71' '--exec-prefix=/opt/alt/php71' '--bindir=/opt/alt/php71/usr/bin' '--sbindir=/opt/alt/php71/usr/sbin' '--sysconfdir=/opt/alt/php71/etc' '--datadir=/opt/alt/php71/usr/share' '--includedir=/opt/alt/php71/usr/include' '--libdir=/opt/alt/php71/usr/lib64' '--libexecdir=/opt/alt/php71/usr/libexec' '--localstatedir=/var' '--with-curl=/opt/alt/curlssl/usr' '--sharedstatedir=/usr/com' '--mandir=/opt/alt/php71/usr/share/man' '--infodir=/opt/alt/php71/usr/share/info' '--cache-file=../config.cache' '--with-libdir=lib64' '--with-config-file-path=/opt/alt/php71/etc' '--with-config-file-scan-dir=/opt/alt/php71/link/conf' '--disable-debug' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-huge-code-pages' '--enable-opcache' '--enable-opcache-file' '--enable-shmop' '--enable-xml' '--with-bz2' '--with-freetype-dir=/usr' '--with-gettext' '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr' '--with-kerberos' '--with-layout=GNU' '--with-libxml-dir=/opt/alt/libxml2/usr' '--with-mhash' '--with-openssl-dir=/opt/alt/openssl' '--with-openssl=/opt/alt/openssl' '--with-pcre-regex=/opt/alt/pcre/usr' '--with-pic' '--with-png-dir=/usr' '--with-readline' '--with-t1lib=/opt/alt/t1lib/usr' '--with-webp-dir=/usr' '--with-xpm-dir=/usr' '--with-zlib' '--with-zlib-dir=/usr' '--without-gdbm' '--without-pear' '--with-pcre-jit' '--enable-pcntl' '--with-litespeed' '--with-recode=shared,/usr' '--without-mysqli' '--disable-mbstring' '--disable-bcmath' '--disable-dba' '--disable-dom' '--disable-fileinfo' '--disable-json' '--disable-intl' '--disable-pdo' '--disable-phar' '--disable-posix' '--disable-soap' '--disable-sockets' '--disable-sysvsem' '--disable-sysvshm' '--disable-sysvmsg' '--disable-wddx' '--disable-xmlreader' '--disable-xmlwriter' '--disable-zip' '--without-gd' '--without-imap' '--without-xmlrpc' '--without-xsl' '--without-ldap' '--without-pgsql' '--without-snmp' '--without-mcrypt' '--without-tidy' '--without-enchant' '--without-recode' '--without-mssql' '--without-pspell' '--without-unixODBC' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'target_alias=x86_64-redhat-linux-gnu'
Server API	LiteSpeed V7.4.3
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/opt/alt/php71/etc
Loaded Configuration File	/opt/alt/php71/etc/php.ini
Scan this dir for additional .ini files	/opt/alt/php71/link/conf
Additional .ini files parsed	/opt/alt/php71/link/conf/alt_php.ini
PHP API	20160303
PHP Extension	20160303
Zend Extension	320160303
Zend Extension Build	API320160303,NTS
PHP Extension Build	API20160303,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	enabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	disabled
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*

curl
cURL support	enabled
cURL Information	7.62.0
Age	4
Features
AsynchDNS	Yes
CharConv	No
Debug	No
GSS-Negotiate	No
IDN	No
IPv6	Yes
krb4	No
Largefile	Yes
libz	Yes
NTLM	Yes
NTLMWB	Yes
SPNEGO	Yes
SSL	Yes
SSPI	No
TLS-SRP	No
HTTP2	Yes
GSSAPI	Yes
KERBEROS5	Yes
UNIX_SOCKETS	Yes
PSL	No
Protocols	dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host	x86_64-redhat-linux-gnu
SSL Version	OpenSSL/1.0.2k
ZLib Version	1.2.3
libSSH Version	libssh2/1.8.0

json
json support	enabled
json version	1.5.0

mbstring
Multibyte Support	enabled
Multibyte string engine	libmbfl
HTTP input encoding translation	disabled
libmbfl version	1.3.2
oniguruma version	5.9.6

dom
DOM/XML	enabled
DOM/XML API Version	20031129
libxml Version	2.9.4
HTML Support	enabled
XPath Support	enabled
XPointer Support	enabled
Schema Support	enabled
RelaxNG Support	enabled

### Additional Information

Not using Composer. Relying on Init.php in GoDaddy environment.  PHP, curl, json, mbstring and DOM are all installed (see Versions, above).

**Comment by moazam1** [comment]
Having same issues. I am working on trestle web api integration. How can you encourage developers to use web api if you don't provide support? Library itself didn't update in 2 years and lack of examples. Really you need to set standards first for coding! There are no checks whether a return response include a field or not.

**Comment by mlacunza** [comment]
> Having same issues. I am working on trestle web api integration. How can you encourage developers to use web api if you don't provide support? Library itself didn't update in 2 years and lack of examples. Really you need to set standards first for coding! There are no checks whether a return response include a field or not.

Agree! I know my comment will not going to help you, but I stop using this lib and start with a PHP framework, using his libs for connect to RETS servers...
